"""Add date_rejected to Request

Revision ID: 431416d9cefe
Revises: 
Create Date: 2025-09-16 19:46:02.036717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431416d9cefe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_rejected', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('date_rejected')

    # ### end Alembic commands ###
